In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# SMOTE

In [113]:
X_train = pd.read_csv("X_train_SMOTE.csv")
y_train = pd.read_csv("Y_train_SMOTE.csv")
X_test = pd.read_csv("test_x.csv")
y_test = pd.read_csv("test_labels.csv")

In [114]:
X_train = X_train.drop(columns=['Unnamed: 0'])

In [115]:
y_train = y_train.drop(columns=['Unnamed: 0'])

In [116]:
y_train = np.ravel(y_train)
y_test = np.ravel(y_test)

In [117]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

model = RandomForestClassifier()

model.fit(X_train,y_train)

param_grid = {
                'n_estimators': [5, 10, 20, 30, 40, 50],
                'max_depth': [2, 7, 12, 17],
                'criterion': ["entropy"],
                'random_state': [0],
             }

grid_clf1 = GridSearchCV(model, param_grid, cv=5, n_jobs=-1)
grid_clf1.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy'], 'max_depth': [2, 7, 12, 17],
                         'n_estimators': [5, 10, 20, 30, 40, 50],
                         'random_state': [0]})

In [118]:
grid_clf1.best_estimator_

RandomForestClassifier(criterion='entropy', max_depth=17, n_estimators=30,
                       random_state=0)

In [119]:
from sklearn.metrics import confusion_matrix,accuracy_score

pred=grid_clf1.best_estimator_.predict(X_test)
cm=confusion_matrix(y_test,pred)
AS=accuracy_score(y_test,pred)

print(cm)
print(AS)

[[158   3   1   0]
 [  1   4   2   0]
 [  1   2   3   0]
 [  1   0   1   7]]
0.9347826086956522


In [120]:
from sklearn.metrics import recall_score
recall_score(y_test,pred, average=None)

array([0.97530864, 0.57142857, 0.5       , 0.77777778])

In [122]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression

LG = LogisticRegression(random_state=0, solver = 'liblinear')

LG.fit(X_train,y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [123]:
from sklearn.metrics import confusion_matrix,accuracy_score
model_LG= LG

pred_LG=model_LG.predict(X_test)
cm=confusion_matrix(y_test,pred_LG)
AS_LG=accuracy_score(y_test,pred_LG)

print(cm)
print(AS_LG)

[[150   5   6   1]
 [  0   4   2   1]
 [  1   3   2   0]
 [  1   0   3   5]]
0.875


In [124]:
from sklearn.metrics import recall_score
recall_score(y_test,pred_LG, average=None)

array([0.92592593, 0.57142857, 0.33333333, 0.55555556])

# not SMOTE

In [125]:
X_train = pd.read_csv("train_x.csv")
y_train = pd.read_csv("train_labels.csv")
X_test = pd.read_csv("test_x.csv")
y_test = pd.read_csv("test_labels.csv")

In [126]:
y_train = np.ravel(y_train)
y_test = np.ravel(y_test)

In [127]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

model = RandomForestClassifier()

model.fit(X_train,y_train)

param_grid = {
                'n_estimators': [5, 10, 20, 30, 40, 50],
                'max_depth': [2, 7, 12, 17],
                'criterion': ["entropy"],
                'random_state': [0],
             }

grid_clf1 = GridSearchCV(model, param_grid, cv=5, n_jobs=-1)
grid_clf1.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy'], 'max_depth': [2, 7, 12, 17],
                         'n_estimators': [5, 10, 20, 30, 40, 50],
                         'random_state': [0]})

In [128]:
grid_clf1.best_estimator_

RandomForestClassifier(criterion='entropy', max_depth=7, n_estimators=40,
                       random_state=0)

In [129]:
from sklearn.metrics import confusion_matrix,accuracy_score

pred=grid_clf1.best_estimator_.predict(X_test)
cm=confusion_matrix(y_test,pred)
AS=accuracy_score(y_test,pred)

print(cm)
print(AS)

[[162   0   0   0]
 [  2   4   1   0]
 [  2   2   2   0]
 [  1   1   2   5]]
0.9402173913043478


In [130]:
from sklearn.metrics import recall_score
recall_score(y_test,pred, average=None)

array([1.        , 0.57142857, 0.33333333, 0.55555556])

In [131]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression

LG = LogisticRegression(random_state=0, solver = 'liblinear')

LG.fit(X_train,y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [133]:
from sklearn.metrics import confusion_matrix,accuracy_score
model_LG= LG

pred_LG=model_LG.predict(X_test)
cm=confusion_matrix(y_test,pred_LG)
AS_LG=accuracy_score(y_test,pred_LG)

print(cm)
print(AS_LG)

[[161   1   0   0]
 [  2   4   1   0]
 [  3   3   0   0]
 [  3   0   2   4]]
0.9184782608695652


In [135]:
from sklearn.metrics import recall_score
recall_score(y_test,pred_LG, average=None)

array([0.99382716, 0.57142857, 0.        , 0.44444444])